package com.workshop.okeatp.mapper;

import com.workshop.okeatp.dataset.Items;
import com.workshop.okeatp.dataset.ItemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    long countByExample(ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int deleteByExample(ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int insert(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int insertSelective(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    List<Items> selectByExample(ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Items record, @Param("example") ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int updateByExample(@Param("record") Items record, @Param("example") ItemsExample example);
}