package com.workshop.okeatp.service;

import com.workshop.okeatp.dataset.ItemsCtd;
import com.workshop.okeatp.dataset.ItemsCtdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemsCtdService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS_CTD
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    long countByExample(ItemsCtdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS_CTD
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int deleteByExample(ItemsCtdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS_CTD
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int insert(ItemsCtd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS_CTD
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int insertSelective(ItemsCtd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS_CTD
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    List<ItemsCtd> selectByExample(ItemsCtdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS_CTD
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") ItemsCtd record, @Param("example") ItemsCtdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEMS_CTD
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int updateByExample(@Param("record") ItemsCtd record, @Param("example") ItemsCtdExample example);
}