package com.workshop.okeatp.service;

import com.workshop.okeatp.dataset.Offers;
import com.workshop.okeatp.dataset.OffersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OffersService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFERS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    long countByExample(OffersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFERS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int deleteByExample(OffersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFERS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int insert(Offers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFERS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int insertSelective(Offers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFERS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    List<Offers> selectByExample(OffersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFERS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Offers record, @Param("example") OffersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFERS
     *
     * @mbg.generated Thu Nov 14 14:44:10 CST 2019
     */
    int updateByExample(@Param("record") Offers record, @Param("example") OffersExample example);
}